---
# bg144.sytes.net
- name: Converge
  hosts: localhost
  become: true

  vars:
    certbot_install_method: 'snap'
    certbot_auto_renew_user: root
    certbot_admin_email: dacino@gmail.com
    certbot_create_method: 'webroot'
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    cerbot_dir: "/etc/letsencrypt/live"
    certbot_certs:
      - email: dacino@gmail.com
        webroot: "/var/www/html"
        domains:
          - bg144.sytes.net
      - domains:
        - bg144.sytes.net
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "bg144.sytes.net"
        root: "/var/www/html"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "certbot_test.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/certbot-test.servercheck.in/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/certbot-test.servercheck.in/privkey.pem;
            ssl_protocols       TLSv1.1 TLSv1.2;
            ssl_ciphers         HIGH:!aNULL:!MD5;

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.git
    - geerlingguy.certbot
    - geerlingguy.nginx
